# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

# Important: the zsh-defer plugin definition should be placed before any plugins that will use the defer template.
# Sheldon always processes plugins in the order they are defined in the config fil
# zsh-defer must be written before any plugins that use the defer template!
[plugins.zsh-defer]
github = "romkatv/zsh-defer"
# Then add a template that calls zsh-defer source instead of just source.
[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

# ---------------------------
# (Other)
# ---------------------------
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

# ---------------------------
# (Repo) × (FPATH) pattern
# ---------------------------
# pattern: Fetch the completion from the repo and add it to the fpath
# If added to the fpath, compinit will pick the completions up.
# So they cannot apply 'defer loading'
[plugins.eza-completion]
remote = "https://raw.githubusercontent.com/eza-community/eza/refs/heads/main/completions/zsh/_eza"
apply = ["fpath"]

[plugins.fd-completion]
remote = "https://raw.githubusercontent.com/sharkdp/fd/refs/heads/master/contrib/completion/_fd"
apply = ["fpath"]

[plugins.ghq-completion]
remote = "https://raw.githubusercontent.com/x-motemen/ghq/refs/heads/master/misc/zsh/_ghq"
apply = ["fpath"]

[plugins.mise-completion]
remote = "https://raw.githubusercontent.com/jdx/mise/refs/heads/main/completions/_mise"
apply = ["fpath"]

[plugins.docker-compose-completion]
remote = "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/refs/heads/master/plugins/docker-compose/_docker-compose"
apply = ["fpath"]

# ---------------------------
# (Repo) × (source) pattern
# ---------------------------
# pattern: Execute 'sources' to the completion from the repo
# They can use 'defer loading', so they help start up zsh more fastly.
# use: please specify the zsh file
[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.sheldon-completion]
remote = "https://raw.githubusercontent.com/rossmacarthur/sheldon/refs/heads/trunk/completions/sheldon.zsh"
apply = ["defer"]


[plugins.gopass-completion]
remote = "https://raw.githubusercontent.com/gopasspw/gopass/refs/heads/master/zsh.completion"
apply = ["defer"]

# ---------------------------
# (Generate) × (FPATH)
# ---------------------------
# pattern: Fetch the completion which is generated by the script from my dotfile-repo and add it to the fpath
# The generation script is created locally, so it can be referenced locally...
# But it is managed remotely (to updated the script regularly via github pipeline)
[plugins.act-completion]
remote = "https://raw.githubusercontent.com/hohihohi/dotfiles/refs/heads/main/dot_zsh.d/completions/_act"
apply = ["fpath"]

[plugins.chezmoi-completion]
remote = "https://raw.githubusercontent.com/hohihohi/dotfiles/refs/heads/main/dot_zsh.d/completions/_chezmoi"
apply = ["fpath"]

[plugins.docker-completion]
remote = "https://raw.githubusercontent.com/hohihohi/dotfiles/refs/heads/main/dot_zsh.d/completions/_docker"
apply = ["fpath"]

[plugins.gh-completion]
remote = "https://raw.githubusercontent.com/hohihohi/dotfiles/refs/heads/main/dot_zsh.d/completions/_gh"
apply = ["fpath"]

[plugins.gibo-completion]
remote = "https://raw.githubusercontent.com/hohihohi/dotfiles/refs/heads/main/dot_zsh.d/completions/_gibo"
apply = ["fpath"]

[plugins.gitleaks-completion]
remote = "https://raw.githubusercontent.com/hohihohi/dotfiles/refs/heads/main/dot_zsh.d/completions/_gitleaks"
apply = ["fpath"]

[plugins.rg-completion]
remote = "https://raw.githubusercontent.com/hohihohi/dotfiles/refs/heads/main/dot_zsh.d/completions/_rg"
apply = ["fpath"]

[plugins.yq-completion]
remote = "https://raw.githubusercontent.com/hohihohi/dotfiles/refs/heads/main/dot_zsh.d/completions/_yq"
apply = ["fpath"]

[plugins.zellij-completion]
remote = "https://raw.githubusercontent.com/hohihohi/dotfiles/refs/heads/main/dot_zsh.d/completions/_zellij"
apply = ["fpath"]

# ---------------------------
# (Generate) × (source)
# ---------------------------
# pattern: Execute 'sources' to the completion which is generated by the script from my dotfile-repo
# The generation script is created locally, so it can be referenced locally...
# But it is managed remotely (to updated the script regularly via github pipeline)
# They can use 'defer loading', so they help start up zsh more fastly.
# use: please specify the zsh file
