# User-configured commands that can be invoked from within Lazygit
# See https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Command_Keybindings.md
customCommands:
  - key: "C"
    context: "files"
    description: "Commit files with commit template(conventional commit)"
    prompts:
      - type: "menu"
        title: "What kind of commit type is it?"
        key: "Type"
        options:
          - name: "feat"
            description: "add, adjust or remove a new feature to the API or UI"
            value: "feat"
          - name: "fix"
            description: "fix an API or UI bug of a preceded feat commit"
            value: "fix"
          - name: "refactor"
            description: "rewrite or restructure code without altering API or UI behavior"
            value: "refactor"
          - name: "perf"
            description: "special type of refactor commits that specifically improve performance"
            value: "perf"
          - name: "style"
            description: "address code style and do not affect application behavior"
            value: "style"
          - name: "test"
            description: "add missing tests or correct existing ones"
            value: "test"
          - name: "docs"
            description: "exclusively affect documentation"
            value: "docs"
          - name: "build"
            description: " affect build-related components such as build tools, dependencies, project version..."
            value: "build"
          - name: "ops"
            description: "affect operational aspects like infrastructure (IaC), deployment scripts, CI/CD pipelines, backups, monitoring, or recovery procedures"
            value: "ops"
          - name: "chore"
            description: "represent tasks like initial commit, modifying .gitignore, ..."
            value: "chore"
        initialValue: "feat"
      - type: "input"
        title: "(Optional) Enter the scope"
        key: "Scope"
        initialValue: ""
      - type: "input"
        title: "Input the description"
        key: "Description"
        initialValue: ""
    command: 'git commit -m "{{ .Form.Type }}{{if .Form.Scope}}({{ .Form.Scope }}){{end}}: {{ .Form.Description }}"'
    loadingText: "Commiting..."
